name: Sergdort-MVVM-Practice

options:
  bundleIdPrefix: jp.co.ryu1fukami

targets:
  Sergdort-MVVM-Practice:
    type: application
    platform: iOS
    sources: Sergdort-MVVM-Practice
    setting:
      base:
        INFOPLIST_FILE: Sergdort-MVVM-Practice-Practice/Resources/Info.plist
    dependencies:
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: RxRelay
      - carthage: APIKit
      - carthage: SkeletonView
      - carthage: RxDataSources
      - carthage: Differentiator

  Sergdort-MVVM-PracticeTests:
    type: bundle.unit-test
    platform: iOS
    sources: Sergdort-MVVM-PracticeTests
    setting:
      base:
        INFOPLIST_FILE: Sergdort-MVVM-Practice-PracticeTests/Info.plist
    dependencies:
      - target: Sergdort-MVVM-Practice
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: RxRelay
      - carthage: RxTest
      - carthage: RxBlocking
      - carthage: APIKit
      - carthage: Quick
      - carthage: Nimble
